nelmio_api_doc:
    documentation:
        info:
            title: Healthcare-CRM
            description: 4th-semester, MVC-web-application-development
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!docs|_error)

